apiVersion: apps/v1
kind: Deployment
metadata:
  name: hz-man
  labels:
    app: hz-man

spec:
  replicas: 1
  selector:
      matchLabels:
        app: hz-man
  template:
    metadata:
      labels:
        app: hz-man
    spec:
      containers:
      - name: hz-manager
        image: hazelcast/management-center:3.12
        env:
        - name: JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true"
        ports:
        - containerPort: 8080
