version: '3'

services:
  streamer-hazelcast-management-center:
    image: hazelcast/management-center:3.12
    ports:
      - 8180:8080
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
          resources:
            limits:
              cpus: "0.1"
              memory: 200M
