version: '3'

services:
  streamer-hazelcast-management-center:
    image: hazelcast/management-center:3.12
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    networks:
      - hz-net
    ports:
      - 8080:8080
#   deploy:
#         replicas: 1
#         restart_policy:
#           condition: on-failure
#         resources:
#           limits:
#             cpus: "0.1"
#             memory: 200M

networks:
  hz-net:
