hazelcast:
  management-center:
      enabled: true
      scripting-enabled: false
      update-interval: 2
      url: http://hz-man:8080/hazelcast-mancenter
  group:
    name: hz-group

  ringbuffer:
    rb_jobs:
      capacity: 10000
      # time-to-live-seconds: 180
      in-memeory-format: BINARY



